#!/bin/bash
# SDM REWARDS - Cron Job Setup Script
# ====================================
# This script sets up the scheduled tasks for the SDM REWARDS platform
# Run as: bash setup_cron.sh

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  SDM REWARDS - Cron Job Setup${NC}"
echo -e "${GREEN}========================================${NC}"

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"
LOG_DIR="/var/log/sdm-rewards"

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${YELLOW}Warning: Not running as root. You may need sudo for some operations.${NC}"
fi

# Create log directory if it doesn't exist
echo -e "${YELLOW}Creating log directory...${NC}"
if [ -d "$LOG_DIR" ]; then
    echo -e "${GREEN}Log directory already exists: $LOG_DIR${NC}"
else
    sudo mkdir -p "$LOG_DIR"
    sudo chmod 755 "$LOG_DIR"
    echo -e "${GREEN}Created log directory: $LOG_DIR${NC}"
fi

# Load environment variables from backend/.env
echo -e "${YELLOW}Loading environment variables...${NC}"
if [ -f "$BACKEND_DIR/.env" ]; then
    export $(grep -v '^#' "$BACKEND_DIR/.env" | xargs)
    echo -e "${GREEN}Environment variables loaded from $BACKEND_DIR/.env${NC}"
else
    echo -e "${RED}Error: $BACKEND_DIR/.env not found${NC}"
    exit 1
fi

# Verify required environment variables
REQUIRED_VARS=("MONGO_URL" "DB_NAME")
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        echo -e "${RED}Error: Required environment variable $var is not set${NC}"
        exit 1
    fi
done
echo -e "${GREEN}All required environment variables are set${NC}"

# Create cron entries
echo -e "${YELLOW}Setting up cron jobs...${NC}"

# Create a temporary cron file
CRON_FILE="/tmp/sdm_rewards_cron"

cat > "$CRON_FILE" << EOF
# SDM REWARDS - Scheduled Tasks
# Generated by setup_cron.sh on $(date)
# ===========================================

# Environment variables for cron
SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
MONGO_URL=${MONGO_URL}
DB_NAME=${DB_NAME}

# Daily notifications - Run at 10:00 AM every day (Ghana time)
0 10 * * * cd $BACKEND_DIR && /usr/bin/python3 scripts/scheduled_tasks.py daily-notifications >> $LOG_DIR/daily-notifications.log 2>&1

# Inactive user reminders - Run at 2:00 PM on Mondays and Thursdays
0 14 * * 1,4 cd $BACKEND_DIR && /usr/bin/python3 scripts/scheduled_tasks.py inactive-reminders 7 >> $LOG_DIR/inactive-reminders.log 2>&1

# Weekly summaries - Run at 9:00 AM every Sunday
0 9 * * 0 cd $BACKEND_DIR && /usr/bin/python3 scripts/scheduled_tasks.py weekly-summaries >> $LOG_DIR/weekly-summaries.log 2>&1

# Security checks - Run at 3:00 AM daily
0 3 * * * cd $BACKEND_DIR && /usr/bin/python3 scripts/scheduled_tasks.py security-checks >> $LOG_DIR/security-checks.log 2>&1

# Log rotation - Clean logs older than 30 days (runs weekly on Sunday at midnight)
0 0 * * 0 find $LOG_DIR -name "*.log" -mtime +30 -delete >> $LOG_DIR/cleanup.log 2>&1

EOF

# Install the cron file
echo -e "${YELLOW}Installing cron jobs...${NC}"
crontab "$CRON_FILE"

# Verify installation
echo -e "${YELLOW}Verifying cron installation...${NC}"
crontab -l

# Cleanup
rm -f "$CRON_FILE"

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Cron Jobs Successfully Configured!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo -e "Scheduled Tasks:"
echo -e "  - Daily Notifications:    10:00 AM every day"
echo -e "  - Inactive Reminders:     2:00 PM on Mon & Thu"
echo -e "  - Weekly Summaries:       9:00 AM every Sunday"
echo -e "  - Security Checks:        3:00 AM every day"
echo ""
echo -e "Log files location: $LOG_DIR"
echo ""
echo -e "${YELLOW}To view logs:${NC}"
echo -e "  tail -f $LOG_DIR/daily-notifications.log"
echo ""
echo -e "${YELLOW}To manually test a task:${NC}"
echo -e "  cd $BACKEND_DIR && python3 scripts/scheduled_tasks.py daily-notifications"
echo ""
